


package stage;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;



import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jxl.Cell;
import jxl.Sheet;

import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.Number;
import jxl.write.WritableCell;
import jxl.write.WritableImage;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import jxl.write.biff.RowsExceededException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class textile extends javax.swing.JFrame {
static int i=0;
private static final double CELL_DEFAULT_HEIGHT = 17;
private static final double CELL_DEFAULT_WIDTH = 64;
static int r;
static ArrayList image;
static boolean modifier;

    /**
     * Creates new form textile
     */
    public final static int BUF_SIZE = 1024;
@SuppressWarnings("empty-statement")
    public textile() {
        
       
        
//       jLabel19.setText(""+Introduction.type);
        image=new ArrayList();
     
        initComponents(); 
        Rapport.setEditable(false);
        

      
           Rapport.setText("psps");
       
  pack();
        
        //a modifier type de rapport si modifier ==true
        thistype.setText("Rapport "+Introduction.typestring);
        JDBC.respo();JDBC.cat();
        java.util.ArrayList cat=new java.util.ArrayList ();
        java.util.ArrayList respo=new java.util.ArrayList ();
              respo  = JDBC.respo;
              cat=JDBC.cat;
                for (int i = 0; i < respo.size(); i++)
      {
         // System.out.println(respo.get(i).toString());
          Rediger.addItem(respo.get(i).toString());
          valider.addItem(respo.get(i).toString());
         // Rediger.addItem(respo.get(i).toString());
        // System.out.println(types.get(i).toString());
      }
                for (int i = 0; i < cat.size(); i++){
                categorie.addItem(cat.get(i).toString());}
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DateR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Rapport = new javax.swing.JTextField();
        DateD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DateRE = new javax.swing.JTextField();
        Demandeur = new javax.swing.JTextField();
        NombreEch = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IdentificationE = new javax.swing.JTextField();
        Prelevement = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        Marque = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Adresseimpo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Importateur = new javax.swing.JTextField();
        Factureaunomde = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Adresse = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        numf = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ICE = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        remise = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        composition = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        PCP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ColorantsAzoiques = new javax.swing.JTextField();
        Metaux = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        images = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        DUM = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Datef = new javax.swing.JTextField();
        Rediger = new javax.swing.JComboBox();
        valider = new javax.swing.JComboBox();
        categorie = new javax.swing.JComboBox();
        thistype = new javax.swing.JTextField();

        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("N° Rapport :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("IDentification Echantillon ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(171, 171, 171)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(316, 316, 316))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        DateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateRActionPerformed(evt);
            }
        });

        jLabel1.setText("N° Rapport :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("IDentification Echantillon ");

        jLabel11.setText("Date de rédaction ");

        Rapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RapportActionPerformed(evt);
            }
        });
        Rapport.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                RapportPropertyChange(evt);
            }
        });

        DateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDActionPerformed(evt);
            }
        });

        jLabel12.setText("Date de réception échantillon");

        jLabel13.setText("Demandeur");

        jLabel14.setText("Nombre échantillons");

        jLabel15.setText("Date de début des essais ");

        DateRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateREActionPerformed(evt);
            }
        });

        Demandeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemandeurActionPerformed(evt);
            }
        });

        NombreEch.setText("0");
        NombreEch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEchActionPerformed(evt);
            }
        });

        jLabel16.setText("Identification échantillion ");

        jLabel17.setText("N° Prelevement ");

        jLabel18.setText("marque/Ref");

        IdentificationE.setText("0");
        IdentificationE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificationEActionPerformed(evt);
            }
        });

        Prelevement.setText("0");
        Prelevement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrelevementActionPerformed(evt);
            }
        });

        jTextField13.setText("0");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        Marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarqueActionPerformed(evt);
            }
        });

        jLabel19.setText("Categorie");

        jLabel20.setText("Rédigé par ");

        jLabel21.setText("Validé par ");

        jPanel3.setForeground(new java.awt.Color(0, 204, 204));

        Adresseimpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseimpoActionPerformed(evt);
            }
        });

        jLabel5.setText("Importateur");

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Facturation ");

        jLabel22.setText("Adresse Importateur");

        Importateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportateurActionPerformed(evt);
            }
        });

        Factureaunomde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactureaunomdeActionPerformed(evt);
            }
        });

        jLabel23.setText("Adresse");

        jLabel26.setText("Facture au nom de ");

        Adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseActionPerformed(evt);
            }
        });

        jLabel29.setText("ICE");

        numf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numfActionPerformed(evt);
            }
        });

        jLabel30.setText("NUM FACTURE");

        ICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICEActionPerformed(evt);
            }
        });

        jLabel31.setText("remise commerciale");

        remise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remiseActionPerformed(evt);
            }
        });

        jLabel32.setText("Composition");

        composition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compositionActionPerformed(evt);
            }
        });

        jPanel4.setForeground(new java.awt.Color(0, 204, 204));

        PCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCPActionPerformed(evt);
            }
        });

        jLabel7.setText("Colorants Azoiques");

        jLabel25.setText("PCP");

        ColorantsAzoiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorantsAzoiquesActionPerformed(evt);
            }
        });

        Metaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetauxActionPerformed(evt);
            }
        });

        jLabel28.setText("Métaux lourds");

        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Sous traitance");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(249, 249, 249)
                        .addComponent(Metaux, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PCP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(225, 225, 225)
                            .addComponent(ColorantsAzoiques, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 118, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ColorantsAzoiques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Metaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))))
        );

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        images.setText("Telecharger lesimages");
        images.setActionCommand("Telecharger_images");
        images.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagesActionPerformed(evt);
            }
        });

        annuler.setText("annuler");
        annuler.setActionCommand("Telecharger_images");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Factureaunomde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Adresseimpo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Importateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ICE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remise, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(composition, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(images, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(Importateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Adresseimpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Factureaunomde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(remise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(composition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(images, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        images.getAccessibleContext().setAccessibleName("telecharger des images");

        jLabel24.setText("N° DUM");

        DUM.setText("0");
        DUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DUMActionPerformed(evt);
            }
        });

        jLabel27.setText("Date de fin des essais ");

        Datef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatefActionPerformed(evt);
            }
        });

        Rediger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));

        valider.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selctionner" }));

        categorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selctionner" }));
        categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieActionPerformed(evt);
            }
        });

        thistype.setEditable(false);
        thistype.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        thistype.setForeground(new java.awt.Color(0, 102, 153));
        thistype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thistypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(268, 268, 268)
                                .addComponent(thistype, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16))
                                        .addGap(175, 175, 175)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IdentificationE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NombreEch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DateR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DateD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DateRE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Rapport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel17))
                                        .addGap(207, 207, 207)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DUM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Prelevement, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Datef, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Marque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Rediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 428, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(thistype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(Prelevement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Rapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(DateR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(DateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(DateRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(NombreEch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(IdentificationE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Datef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(Marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(Rediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(DUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 439, 439))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void DatefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatefActionPerformed

    private void MetauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MetauxActionPerformed

    private void ColorantsAzoiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorantsAzoiquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorantsAzoiquesActionPerformed

    private void PCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCPActionPerformed

    private void DUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DUMActionPerformed

    private void compositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compositionActionPerformed

    private void remiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remiseActionPerformed

    private void ICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICEActionPerformed

    private void numfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
       
        Textilee t1=new Textilee(
            Integer.parseInt( jTextField13.getText()),
            DateR.getText(),
            DateD.getText(),
            DateRE.getText(),
            Datef.getText(),
            Demandeur.getText(),
            Integer.parseInt(NombreEch.getText()),
            Integer.parseInt(IdentificationE.getText()),
            Integer.parseInt(Prelevement.getText())
            ,Marque.getText(),categorie.getSelectedItem().toString(),
            Rediger.getSelectedItem().toString(),
            
            valider.getSelectedItem().toString() ,
            Integer.parseInt(DUM.getText()),
            Importateur.getText(),
            Factureaunomde.getText(),
            Adresse.getText(),
            0,
            ColorantsAzoiques.getText(),
            PCP.getText()
            ,Metaux.getText());
        JDBC j=new JDBC();
        if(j.rapport_exist(r)){
             JOptionPane optionPane = new JOptionPane("rapport deja exist cliquer sur annuler ensuite gerer les rapport qui exist deja dans la base de données  ", JOptionPane.ERROR_MESSAGE);    
JDialog dialog = optionPane.createDialog("Failure");
dialog.setAlwaysOnTop(true);
dialog.setVisible(true);
        }
        else{
            
           
        if(j.verifier(t1.Rapport)==false && imageLoad.images.size()>=0){
           
            try {
                
                copy(t1); 
                for (int  i=0 ;i< imageLoad.images.size();i++){
                    
                    
                    j.save(imageLoad.images.get(i).toString(),"",t1.Rapport);}
                sheet1(t1);
                sheet2(t1);
                
                try {
                    
                    sheet3(t1);
                } catch (IOException ex) {
                    Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
                } catch (BiffException ex) {
                    Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
                } catch (WriteException ex) {
                    Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
                }
                
              
                System.out.println("if");
                j.save_rapport(t1.Rapport);
                String place="C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile";
             
                try {
                    JDBC.converter(t1.Rapport, place);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                JDBC.delete(place+t1.Rapport+".xls");
                JDBC.pdf_to_blob_insert(t1.Rapport);
                JDBC.delete(place+t1.Rapport+".pdf");
                
                this.hide();
                new aprespage_1().setVisible(true);
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            
        
    }//GEN-LAST:event_jButton1ActionPerformed
        else if(imageLoad.images.size()==0){
            
            try {
                copy(t1);
                sheet1(t1);
                sheet2(t1);
               
                this.hide();
                System.out.println("else if");
                j.save_rapport(t1.Rapport);
                
                
                new aprespage_1().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
        
            int result = JOptionPane.showConfirmDialog(null, 
   "vous avez deja depassez les 3 images necessaiires dans ce rapport veuillez contacter l'administrateur continuer sans enregistrement des images ",null, JOptionPane.YES_NO_OPTION);
if(result == JOptionPane.YES_OPTION) {
    imageLoad.images.clear();
    
    /* copy(t1);
        sheet1(t1);
        sheet2(t1);
        this.hide();
        new aprespage_1().setVisible(true);*/
        
   
} 
if(result == JOptionPane.NO_OPTION){
    JOptionPane.getRootFrame().dispose(); 
    this.hide();
    new Introduction().setVisible(true);
}
        

        }

    }
    }
    private void AdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseActionPerformed

    private void FactureaunomdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactureaunomdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FactureaunomdeActionPerformed

    private void ImportateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImportateurActionPerformed

    private void AdresseimpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseimpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseimpoActionPerformed

    private void MarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarqueActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void PrelevementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrelevementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrelevementActionPerformed

    private void IdentificationEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificationEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificationEActionPerformed

    private void NombreEchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEchActionPerformed

    private void DemandeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemandeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemandeurActionPerformed

    private void DateREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateREActionPerformed

    private void DateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDActionPerformed

    private void RapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RapportActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RapportActionPerformed

    private void DateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateRActionPerformed

    private void categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieActionPerformed

    private void thistypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thistypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thistypeActionPerformed

    private void imagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagesActionPerformed
        // TODO add your handling code here:
        r=Integer.parseInt(jTextField13.getText());
        ImagesLoading a = new ImagesLoading(); 
        
        a.initialize();  
        
        
    }//GEN-LAST:event_imagesActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        JDBC j=new JDBC();
        
    try {
        j.annuler_rapport ( r );
        this.hide();
         new Introduction().setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_annulerActionPerformed

    private void RapportPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_RapportPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RapportPropertyChange

    /**
     * @param args the command line arguments
     */
    public void copy(Textilee t1){
         WritableWorkbook workbook = null;

        FileSystem system = FileSystems.getDefault();
        Path original = system.getPath("C:\\Users\\PC\\Desktop\\stage\\Stage\\src\\stage\\Book.xls");
        Path target = system.getPath("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls");

        try {
            Workbook workbook1 = null;
            // Throws an exception if the original file is not found.
            Files.copy(original, target, StandardCopyOption.REPLACE_EXISTING);} catch (IOException ex) {
        Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public void sheet1(Textilee t1){
       

        try {
          
         //   Workbook aWorkBook = Workbook.getWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"));
            
WorkbookSettings ws = new WorkbookSettings();
ws.setEncoding("Cp1252");
Workbook aWorkBook = Workbook.getWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"), ws);
WritableWorkbook aCopy = Workbook.createWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"), aWorkBook);
            WritableSheet aCopySheet = aCopy.getSheet(0);//index of the needed sheet

            //Rapport
            WritableCell aWritableCell = aCopySheet.getWritableCell(1,1);//no need!
            jxl.write.Label anotherWritableCell =  new jxl.write.Label(1,1 ,t1.Rapport+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell);

            
            //date de redaction
            WritableCell aWritableCell1 = aCopySheet.getWritableCell(1,2);//no need!
            jxl.write.Label anotherWritableCell1 =  new jxl.write.Label(1,2 ,t1.Date_de_rédaction);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell1);

            //date de debut des essais
            WritableCell aWritableCell2 = aCopySheet.getWritableCell(1,3);//no need!
            jxl.write.Label anotherWritableCell2 =  new jxl.write.Label(1,3 ,t1.Date_de_début_des_essais);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell2);

            //date de reception echantillon

            WritableCell aWritableCell3 = aCopySheet.getWritableCell(1,4);//no need!
            jxl.write.Label anotherWritableCell3 =  new jxl.write.Label(1,4 ,t1.Date_de_réception_échantillon);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell3);

            //reception

            WritableCell aWritableCell4 = aCopySheet.getWritableCell(1,5);//no need!
            jxl.write.Label anotherWritableCell4 =  new jxl.write.Label(1,5 ,t1.Date_de_fin_des_essais);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell4);

            //demandeur

            WritableCell aWritableCell5 = aCopySheet.getWritableCell(1,6);//no need!
            jxl.write.Label anotherWritableCell5 =  new jxl.write.Label(1,6 ,t1.Demandeur);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell5);

            //DUM

            WritableCell aWritableCell6 = aCopySheet.getWritableCell(1,7);//no need!
            jxl.write.Label anotherWritableCell6 =  new jxl.write.Label(1,7 ,t1.DUM+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell6);
            //nbr ech
            WritableCell aWritableCell7 = aCopySheet.getWritableCell(1,8);//no need!
            jxl.write.Label anotherWritableCell7 =  new jxl.write.Label(1,8 ,NombreEch.getText()+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell7);

            // id ech

            WritableCell aWritableCell8 = aCopySheet.getWritableCell(1,9);//no need!
            jxl.write.Label anotherWritableCell8 =  new jxl.write.Label(1,9 ,t1.Identification_échantillion+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell8);

            //prelevement
            WritableCell aWritableCell9 = aCopySheet.getWritableCell(1,10);//no need!
            jxl.write.Label anotherWritableCell9 =  new jxl.write.Label(1,10 ,t1.Prelevement+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell9);

            // marque
            WritableCell aWritableCell10 = aCopySheet.getWritableCell(1,11);//no need!
            jxl.write.Label anotherWritableCell10 =  new jxl.write.Label(1,11 ,t1.marque_Ref);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell10);

            //categorie

            WritableCell aWritableCell11 = aCopySheet.getWritableCell(1,12);//no need!
            jxl.write.Label anotherWritableCell11 =  new jxl.write.Label(1,12 ,t1.Categorie);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell11);
            // rediger par

            WritableCell aWritableCell12 = aCopySheet.getWritableCell(1,13);//no need!
            jxl.write.Label anotherWritableCell12 =  new jxl.write.Label(1,13 ,t1.Rédigé_par);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell12);

            //valider par
            WritableCell aWritableCell13 = aCopySheet.getWritableCell(1,14);//no need!
            jxl.write.Label anotherWritableCell13 =  new jxl.write.Label(1,14 ,t1.Validé_par);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell13);

            // importateur
            WritableCell aWritableCell14 = aCopySheet.getWritableCell(1,16);//no need!
            jxl.write.Label anotherWritableCell14 =  new jxl.write.Label(1,16 ,t1.Importateur);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell14);

            // adresse imp

            WritableCell aWritableCell15 = aCopySheet.getWritableCell(1,17);//no need!
            jxl.write.Label anotherWritableCell15 =  new jxl.write.Label(1,17 ,Adresseimpo.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell15);

            //facture

            WritableCell aWritableCell16 = aCopySheet.getWritableCell(1,18);//no need!
            jxl.write.Label anotherWritableCell16 =  new jxl.write.Label(1,18 ,t1.Facture_au_nom_de);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell16);
            //adresse
            WritableCell aWritableCell17 = aCopySheet.getWritableCell(1,19);//no need!
            jxl.write.Label anotherWritableCell17 =  new jxl.write.Label(1,19 ,Adresse.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell17);

            // ICE

            WritableCell aWritableCell18 = aCopySheet.getWritableCell(1,20);//no need!
            jxl.write.Label anotherWritableCell18 =  new jxl.write.Label(1,20 ,ICE.getText()+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell18);

            //NUM FACTURE
            WritableCell aWritableCell19 = aCopySheet.getWritableCell(1,21);//no need!
            jxl.write.Label anotherWritableCell19 =  new jxl.write.Label(1,21 ,numf.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell19);

            //remise commerciale
           
            
            WritableCell aWritableCell20 = aCopySheet.getWritableCell(1,22);//no need!
            jxl.write.Label anotherWritableCell20 =  new jxl.write.Label(1,22 ,remise.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell20);
            //Etiquetage 
            WritableCell aWritableCell21 = aCopySheet.getWritableCell(1,23);//no need!
            jxl.write.Label anotherWritableCell21 =  new jxl.write.Label(1,23 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell21);

            
            
            
            //composition
               WritableCell aWritableCell22 = aCopySheet.getWritableCell(1,24);//no need!
            jxl.write.Label anotherWritableCell22 =  new jxl.write.Label(1,24 ,composition.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell22);
            
            
             //PH
               WritableCell aWritableCell23 = aCopySheet.getWritableCell(1,25);//no need!
            jxl.write.Label anotherWritableCell23 =  new jxl.write.Label(1,25 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell23);
             //colorant azoique 
               WritableCell aWritableCell24 = aCopySheet.getWritableCell(1,26);//no need!
            jxl.write.Label anotherWritableCell24 =  new jxl.write.Label(1,26 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell24);
            
             //form
               WritableCell aWritableCell25 = aCopySheet.getWritableCell(1,27);//no need!
            jxl.write.Label anotherWritableCell25 =  new jxl.write.Label(1,27 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell25);
            
             //pcp
               WritableCell aWritableCell26 = aCopySheet.getWritableCell(1,28);//no need!
            jxl.write.Label anotherWritableCell26 =  new jxl.write.Label(1,28 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell26);
            
             //metaux 
               WritableCell aWritableCell27 = aCopySheet.getWritableCell(1,29);//no need!
            jxl.write.Label anotherWritableCell27 =  new jxl.write.Label(1,29 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell27);
            
             //Nickel 
               WritableCell aWritableCell28 = aCopySheet.getWritableCell(1,30);//no need!
            jxl.write.Label anotherWritableCell28 =  new jxl.write.Label(1,30 ,"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell28);
            
            //CA
             
               WritableCell aWritableCell29 = aCopySheet.getWritableCell(1,32);//no need!
            jxl.write.Label anotherWritableCell29 =  new jxl.write.Label(1,32 ,t1.Colorants_Azoiques);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell29);
            
            
            //PCP
                
               WritableCell aWritableCell30 = aCopySheet.getWritableCell(1,33);//no need!
            jxl.write.Label anotherWritableCell30 =  new jxl.write.Label(1,33 ,PCP.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell30);
            
          
            
            //metaux
               WritableCell aWritableCell31 = aCopySheet.getWritableCell(1,34);//no need!
            jxl.write.Label anotherWritableCell31 =  new jxl.write.Label(1,34 ,Metaux.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell31);
            
            
            aCopy.write();

            aCopy.close();
            

        } catch (IOException ex) {
            System.out.println(ex.toString());

        } catch (BiffException ex) {
            Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       
    }
    
    
    public void modifiersheet2(Textilee t1) throws IOException, BiffException, WriteException, ClassNotFoundException, SQLException{
    
      Workbook aWorkBook = Workbook.getWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"));
            WritableWorkbook aCopy = Workbook.createWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"), aWorkBook);

            WritableSheet aCopySheet = aCopy.getSheet(1);//index of the needed sheet}
         //    JDBC.read_image("C:\\Users\\PC\\Desktop\\stage\\Stage\\temp",aCopySheet,t1);
            ArrayList a=JDBC.read_image("C:\\Users\\PC\\Desktop\\stage\\Stage\\temp", aCopySheet, t1);
            System.out.println(a.size());
            
            for(int i=0;i<=1;i++){
              System.out.println((String)a.get(i));  
           JDBC.insert_to(aCopySheet, (String) a.get(i),t1);
            }
           aCopy.write();
            aCopy.close();
            
    }
    public void sheet2(Textilee t1) throws ClassNotFoundException, SQLException{
        
         try {
          
            Workbook aWorkBook = Workbook.getWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"));
            WritableWorkbook aCopy = Workbook.createWorkbook(new File("C:\\Users\\PC\\Desktop\\stage\\Stage\\Rapport_textile\\Rapport_textile"+t1.Rapport+".xls"), aWorkBook);

            WritableSheet aCopySheet = aCopy.getSheet(1);//index of the needed sheet

              //daterapport
            SimpleDateFormat formatter= new SimpleDateFormat("dd-MM-yyyy ");
            Date date = new Date(System.currentTimeMillis());

             WritableCell aWritableCell0 = aCopySheet.getWritableCell(7,4);//no need!
            jxl.write.Label anotherWritableCell0 =  new jxl.write.Label(7,4 ,formatter.format(date));
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell0);
            //
            //Rapport
            WritableCell aWritableCell = aCopySheet.getWritableCell(2,6);//no need!
            jxl.write.Label anotherWritableCell =  new jxl.write.Label(2,6 ,t1.Rapport+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell);
           // importateur
            WritableCell aWritableCell2 = aCopySheet.getWritableCell(2,9);//no need!
            jxl.write.Label anotherWritableCell2 =  new jxl.write.Label(2,9 ,t1.Importateur+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell2);
            
            //adresse
             WritableCell aWritableCell3 = aCopySheet.getWritableCell(2,10);//no need!
            jxl.write.Label anotherWritableCell3 =  new jxl.write.Label(2,10 ,t1.Adresse);
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell3);
            
            
            //prelevement
             WritableCell aWritableCell4 = aCopySheet.getWritableCell(2,11);//no need!
            jxl.write.Label anotherWritableCell4 =  new jxl.write.Label(2,11 ,t1.Prelevement+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell4);
            
            //demandeur 
            
            WritableCell aWritableCell5 = aCopySheet.getWritableCell(2,12);//no need!
            jxl.write.Label anotherWritableCell5 =  new jxl.write.Label(2,12 ,t1.Demandeur+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell5);
            
            // date_de_reception
             WritableCell aWritableCell6 = aCopySheet.getWritableCell(2,13);//no need!
            jxl.write.Label anotherWritableCell6 =  new jxl.write.Label(2,13 ,DateRE.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell6);
            
            //DUM
            WritableCell aWritableCell7 = aCopySheet.getWritableCell(2,14);//no need!
            jxl.write.Label anotherWritableCell7 =  new jxl.write.Label(2,14 ,t1.DUM+"");
            //position of the new cell in column,row            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell7);
            
            //DUM
            WritableCell aWritableCell8 = aCopySheet.getWritableCell(2,15);//no need!
            jxl.write.Label anotherWritableCell8 =  new jxl.write.Label(2,15 ,NombreEch.getText());
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell8);
            
            //id
            WritableCell aWritableCell9 = aCopySheet.getWritableCell(2,16);//no need!
            jxl.write.Label anotherWritableCell9 =  new jxl.write.Label(2,16 ,t1.Identification_échantillion+"");
            //position of the new cell in column,row
            //can be a new Label() or new Number() or new Formula
            aCopySheet.addCell(anotherWritableCell9);
          // JDBC.read_image("C:\\Users\\PC\\Desktop\\stage\\Stage\\temp",aCopySheet,t1);
         //   ArrayList a=JDBC.read_image("C:\\Users\\PC\\Desktop\\stage\\Stage\\temp", aCopySheet, t1);
      /*   for(int i=0;i<=3;i++){
             
             
             JDBC.insert_to(aCopySheet, (String) a.get(i),t1);
             
         }   
            */
        //  JDBC.insert_to( aCopySheet,"C:\\Users\\PC\\Desktop\\téléchargement.jpg",t1);
          //  JDBC.insert_to( aCopySheet,"C:\\Users\\PC\\Desktop\\بمنتبه.jpg", t1);
            
            JDBC.y_a(JDBC.read_image("C:\\Users\\PC\\Desktop\\stage\\Stage\\temp", aCopySheet, t1), aCopySheet, t1);
            
            aCopy.write();
            aCopy.close();
            
           

        }
         catch (IOException ex) {
            System.out.println(ex.toString());

        }
         catch (BiffException ex) {
            Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
        } 
         catch (WriteException ex) {
            Logger.getLogger(textile.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       
    }
    
    public void sheet3(Textilee t1) throws IOException, BiffException, WriteException {
          
     
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adresse;
    private javax.swing.JTextField Adresseimpo;
    private javax.swing.JTextField ColorantsAzoiques;
    private javax.swing.JTextField DUM;
    private javax.swing.JTextField DateD;
    private javax.swing.JTextField DateR;
    private javax.swing.JTextField DateRE;
    private javax.swing.JTextField Datef;
    private javax.swing.JTextField Demandeur;
    private javax.swing.JTextField Factureaunomde;
    private javax.swing.JTextField ICE;
    private javax.swing.JTextField IdentificationE;
    private javax.swing.JTextField Importateur;
    private javax.swing.JTextField Marque;
    private javax.swing.JTextField Metaux;
    private javax.swing.JTextField NombreEch;
    private javax.swing.JTextField PCP;
    private javax.swing.JTextField Prelevement;
    private javax.swing.JTextField Rapport;
    private javax.swing.JComboBox Rediger;
    private javax.swing.JButton annuler;
    private javax.swing.JComboBox categorie;
    private javax.swing.JTextField composition;
    private javax.swing.JButton images;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField numf;
    private javax.swing.JTextField remise;
    private javax.swing.JTextField thistype;
    private javax.swing.JComboBox valider;
    // End of variables declaration//GEN-END:variables

  public int   getrapp(){
        return Integer.parseInt( this.Rapport.getText());
  }
  public  void set(int r ){
      this.Rapport.setText(""+r);
  }
  public void etatrap(){
      if(modifier){
Rapport.disable();}
     }
}
